name: Deploy Worker 

on:
  workflow_run:
    workflows: [Upstream Sync]
    types: [completed]
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Wrangler
        run: |
          npm install -g wrangler
          mv 明文源码.js worker.js
      - name: Deploy Worker for ${{ github.ref_name }} 
        run: |
          wrangler deploy ./worker.js --minify --name=square-snowflake-e53e --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"zijian_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:${{ secrets.TOKEN }} URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}

      - name: Deploy Worker for ${{ github.ref_name }} MIKURU
        run: |
          wrangler deploy ./worker.js --minify --name=muddy-firefly-4af6 --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"miku_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:nYMU6Xk61WsKCCXF941K URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MIKURU }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_MIKURU }}

      - name: Deploy Worker for ${{ github.ref_name }} MESA
        run: |
          wrangler deploy ./worker.js --minify --name=late-firefly-104f --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"mesa_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:9g4C1UAZeaBQD86WfCV0 URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MESA }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_MESA }}

      - name: Deploy Worker for ${{ github.ref_name }} MYTO
        run: |
          wrangler deploy ./worker.js --minify --name=shy-lab-09b8 --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"myto_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:jJh3s4xu97d5eNPi7e0T URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MYTO }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_MYTO }}

      - name: Deploy Worker for ${{ github.ref_name }} SORRY
        run: |
          wrangler deploy ./worker.js --minify --name=raspy-night-e359 --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"sorry_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:6oFtgiYFBA77zDwFRA4b URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_SORRY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_SORRY }}

      - name: Deploy Worker for ${{ github.ref_name }} ARRBU
        run: |
          wrangler deploy ./worker.js --minify --name=floral-darkness-1f83 --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"arrbu_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:Y1JRPHZXm4LXM6R9MRzi URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_ARRBU }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_ARRBU }}

      - name: Deploy Worker for ${{ github.ref_name }} ENNYFE
        run: |
          wrangler deploy ./worker.js --minify --name=sweet-moon-2e38 --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"ennyfe_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:wen1u1aHn4kahKQeQN8j URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_ENNYFE }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_ENNYFE }}

      - name: Deploy Worker for ${{ github.ref_name }} MIKUYO
        run: |
          wrangler deploy ./worker.js --minify --name=white-tooth-a389 --compatibility-date=${{ secrets.DATE }} --var SUB:${{ secrets.SUB }} SUBAPI:${{ secrets.SUBAPI }} SUBCONFIG:${{ secrets.SUBCONFIG }} SUBNAME:"mikuyo_dingyue" TGID:${{ secrets.TGID }} TGTOKEN:${{ secrets.TGTOKEN }} TOKEN:xe3K5Bi0FsU2VxAb5aXi URL:${{ secrets.URL }} RPROXYIP:true
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MIKUYO }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_MIKUYO }}

      - name: mv name
        run: |
          mv worker.js _worker.js

      - name: Deploy Worker for ${{ github.ref_name }} PAGES_1
        run: |
          rm -rf .env
          echo "SUB=${{ secrets.SUB }}" >> .env
          echo "SUBAPI=${{ secrets.SUBAPI }}" >> .env
          echo "SUBCONFIG=${{ secrets.SUBCONFIG }}" >> .env
          echo "SUBNAME=mikuyo_dingyue" >> .env
          echo "TGID=${{ secrets.TGID }}" >> .env
          echo "TGTOKEN=${{ secrets.TGTOKEN }}" >> .env
          echo "TOKEN=N49o8kZF0qp0447j3kyc" >> .env
          echo "URL=${{ secrets.URL }}" >> .env
          echo "RPROXYIP=true" >> .env
          wrangler pages deploy . --project-name=g5w2d5g4
        env:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PAGES_1 }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES_1 }}
