name: updateMessage

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  obfuscate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: node

      - name: Install dependencies
        run: npm install node-fetch axios

      - name: Obfuscate code
        run: node tg.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID_MIKURU: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MIKURU }}
          CLOUDFLARE_API_TOKEN_MIKURU: ${{ secrets.CLOUDFLARE_API_TOKEN_MIKURU }}
          CLOUDFLARE_ACCOUNT_ID_MESA: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MESA }}
          CLOUDFLARE_API_TOKEN_MESA: ${{ secrets.CLOUDFLARE_API_TOKEN_MESA }}
          CLOUDFLARE_ACCOUNT_ID_MYTO: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MYTO }}
          CLOUDFLARE_API_TOKEN_MYTO: ${{ secrets.CLOUDFLARE_API_TOKEN_MYTO }}
          CLOUDFLARE_ACCOUNT_ID_SORRY: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_SORRY }}
          CLOUDFLARE_API_TOKEN_SORRY: ${{ secrets.CLOUDFLARE_API_TOKEN_SORRY }}
          CLOUDFLARE_ACCOUNT_ID_ARRBU: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_ARRBU }}
          CLOUDFLARE_API_TOKEN_ARRBU: ${{ secrets.CLOUDFLARE_API_TOKEN_ARRBU }}
          CLOUDFLARE_ACCOUNT_ID_ENNYFE: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_ENNYFE }}
          CLOUDFLARE_API_TOKEN_ENNYFE: ${{ secrets.CLOUDFLARE_API_TOKEN_ENNYFE }}
          CLOUDFLARE_ACCOUNT_ID_MIKUYO: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_MIKUYO }}
          CLOUDFLARE_API_TOKEN_MIKUYO: ${{ secrets.CLOUDFLARE_API_TOKEN_MIKUYO }}
          CLOUDFLARE_ACCOUNT_ID_PAGES_1: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PAGES_1 }}
          CLOUDFLARE_API_TOKEN_PAGES_1: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES_1 }}
          CLOUDFLARE_ACCOUNT_ID_PAGES_2: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PAGES_2 }}
          CLOUDFLARE_API_TOKEN_PAGES_2: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES_2 }}
          CLOUDFLARE_ACCOUNT_ID_PAGES_3: ${{ secrets.CLOUDFLARE_ACCOUNT_ID_PAGES_3 }}
          CLOUDFLARE_API_TOKEN_PAGES_3: ${{ secrets.CLOUDFLARE_API_TOKEN_PAGES_3 }}
          
          
          
